# Generated by Django 5.2.4 on 2025-07-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='listing_photos/'),
        ),
    ]
