# Generated by Django 5.2.4 on 2025-07-24 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='region',
        ),
        migrations.AlterField(
            model_name='listing',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.location'),
        ),
    ]
