# Generated by Django 5.2.4 on 2026-03-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_listing_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='delivery_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
