# Generated by Django 5.2.4 on 2026-03-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_category_delivery_price_location_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='promoted_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='report_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='reported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
