# Generated by Django 5.2.4 on 2026-04-22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_listing_report_message'),
        ('orders', '0002_order_delivery_price_order_final_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CanceledOrderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_order_id', models.PositiveIntegerField(db_index=True)),
                ('city', models.CharField(max_length=100)),
                ('delivery_price', models.PositiveIntegerField(default=0)),
                ('final_price', models.PositiveIntegerField(default=0)),
                ('paid', models.BooleanField(default=False)),
                ('order_created_at', models.DateTimeField()),
                ('canceled_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canceled_orders', to='listings.listing')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canceled_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
